const BM_SUPABASE_URL='https://pmvvawbaqylspxfmxezw.supabase.co';
const BM_SUPABASE_KEY='sb_publishable_CveglntZGjChE89lPcsQcg_EvBnYmKo';
const BM_SESSION_KEY='barberium_scalabrini_session_v1';
const BM_SHOP='scalabrini-barbieri';
const BM_UNIT='braganca-paulista';
let bmBusy=false,bmTimer=null;
const bmMoney=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(c)||0)/100);
const bmDate=v=>{if(!v)return'—';const s=String(v).slice(0,10),[y,m,d]=s.split('-');return y&&m&&d?`${d}/${m}/${y}`:s};
const bmEsc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const bmStatus=v=>({active:'Ativo',pending:'Pendente',paused:'Pausado',overdue:'Atrasado',cancelled:'Cancelado',expired:'Vencido',paid:'Pago'})[v]||v;
function bmSession(){try{return JSON.parse(localStorage.getItem(BM_SESSION_KEY)||'null')}catch{return null}}
async function bmRpc(name,payload={}){const r=await fetch(`${BM_SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:BM_SUPABASE_KEY,Authorization:`Bearer ${BM_SUPABASE_KEY}`},body:JSON.stringify(payload)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||'Erro ao carregar');return d}
function bmPlanCard(m,state={}){
  const allocations=m.credits||[];
  const current=(m.cycles||[]).find(c=>['pending','overdue'].includes(c.status))||(m.cycles||[])[0];
  const requests=state.action_requests||[];const pausePending=requests.some(r=>r.action_type==='pause'&&r.status==='pending');const cancelPending=requests.some(r=>r.action_type==='cancel'&&r.status==='pending');const rules=state.rules||m.rules||{};
  const benefitHtml=allocations.length?allocations.map(c=>m.plan_type==='subscription'?`<div><span>${bmEsc(c.service)}</span><strong>${c.unlimited?'Ilimitado no ciclo':`${c.available} uso${c.available===1?'':'s'} restante${c.available===1?'':'s'}`}</strong><small>${c.unlimited?'Benefício válido enquanto o ciclo estiver ativo':`${c.used} realizado${c.used===1?'':'s'} • ${c.reserved} reservado${c.reserved===1?'':'s'} neste ciclo`}</small></div>`:`<div><span>${bmEsc(c.service)}</span><strong>${c.unlimited?'Ilimitado':`${c.available} crédito${c.available===1?'':'s'} disponível${c.available===1?'':'is'}`}</strong><small>${c.unlimited?'Benefício sem quantidade fixa':`${c.used} usado${c.used===1?'':'s'} • ${c.reserved} reservado${c.reserved===1?'':'s'}`}${c.expires_on?` • vence ${bmDate(c.expires_on)}`:''}</small></div>`).join(''):`<div><span>${m.plan_type==='subscription'?'Benefícios':'Créditos'}</span><strong>Aguardando pagamento integral</strong><small>O plano só é ativado após a confirmação do pagamento completo.</small></div>`;
  const actionMeta=m.plan_type==='subscription'?`${state.paused_until?`<span><small>Pausa</small><strong>Até ${bmDate(state.paused_until)}</strong></span>`:''}${state.renewal_blocked?`<span><small>Cancelamento</small><strong>${state.cancel_effective_on?`Programado para ${bmDate(state.cancel_effective_on)}`:'Programado'}</strong></span>`:''}`:'';
  const actions=m.plan_type==='subscription'&&['active','paused','overdue'].includes(m.status)?`<div class="bm-plan-actions">${rules.allow_pause!==false&&m.status==='active'&&!pausePending?`<button class="bm-button secondary" data-bm-pause="${m.id}" data-min="${rules.pause_min_days??''}" data-max="${rules.pause_max_days??''}">Solicitar pausa</button>`:''}${pausePending?'<button class="bm-button muted" disabled>Pausa solicitada</button>':''}${rules.allow_cancel!==false&&!state.renewal_blocked&&!cancelPending?`<button class="bm-button danger" data-bm-cancel="${m.id}">Solicitar cancelamento</button>`:''}${cancelPending?'<button class="bm-button muted" disabled>Cancelamento solicitado</button>':''}</div>`:'';
  return `<article class="bm-plan-card"><div class="bm-plan-head"><div><span class="bm-pill ${m.status==='overdue'?'warn':''}">${bmStatus(m.status)}</span><h3>${bmEsc(m.name)}</h3><p>${m.plan_type==='subscription'?'Assinatura por período':'Pacote de créditos'} • ${bmMoney(m.price_cents)}</p></div></div><div class="bm-plan-meta"><span><small>${m.plan_type==='subscription'?'Adesão':'Compra'}</small><strong>${m.started_at?bmDate(m.started_at):'Aguardando pagamento'}</strong></span>${m.valid_until?`<span><small>Validade</small><strong>${bmDate(m.valid_until)}</strong></span>`:''}${m.current_cycle_end?`<span><small>Ciclo atual até</small><strong>${bmDate(m.current_cycle_end)}</strong></span>`:''}${current&&['pending','overdue'].includes(current.status)?`<span class="bm-debt"><small>Mensalidade</small><strong>${bmStatus(current.status)} • vence ${bmDate(current.due_date)}</strong>${current.grace_until&&current.status!=='paid'?`<em>Tolerância até ${bmDate(current.grace_until)}</em>`:''}</span>`:''}${actionMeta}</div><div class="bm-credits">${benefitHtml}</div>${actions}</article>`;
}

function bmPublicPlanCard(p,requests,hasType){const pending=requests.some(r=>r.plan_id===p.id&&r.status==='pending');return `<article class="bm-offer-card"><span class="bm-pill">${p.plan_type==='subscription'?'Assinatura':'Pacote'}</span><h3>${bmEsc(p.name)}</h3>${p.description?`<p>${bmEsc(p.description)}</p>`:''}<strong class="bm-price">${bmMoney(p.price_cents)}${p.plan_type==='subscription'?'<small>/ciclo</small>':''}</strong><div class="bm-benefits">${(p.benefits||[]).map(b=>`<span>✓ ${bmEsc(b.service)} — ${b.unlimited?(p.plan_type==='subscription'?'Ilimitado no ciclo':'Créditos ilimitados'):(p.plan_type==='subscription'?`até ${b.quantity} uso${b.quantity===1?'':'s'}/ciclo`:`${b.quantity} crédito${b.quantity===1?'':'s'}`)}${b.min_days_between?` • intervalo ${b.min_days_between}d`:''}${b.max_per_week?` • máx. ${b.max_per_week}/sem`:''}${b.max_per_month?` • máx. ${b.max_per_month}/mês`:''}</span>`).join('')}</div>${pending?'<button class="bm-button muted" disabled>Solicitação enviada</button>':hasType?'<button class="bm-button muted" disabled>Você já possui um plano deste tipo</button>':`<button class="bm-button" data-bm-request="${p.id}">Quero este plano</button>`}</article>`}
async function bmInject(){
  const profileView=document.querySelector('[data-view="profile"]');const root=document.querySelector('#profileContent');if(!profileView?.classList.contains('active')||!root||root.querySelector('#bmMembershipSection')||bmBusy)return;bmBusy=true;
  try{
    const session=bmSession();const plans=await bmRpc('barberium_public_membership_plans',{p_barbershop_slug:BM_SHOP,p_unit_slug:BM_UNIT});let portal={memberships:[],membership_requests:[]},states=[];
    if(session?.access_token){await bmRpc('barberium_customer_refresh_membership_states',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token});[portal,states]=await Promise.all([bmRpc('barberium_get_customer_portal',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token}),bmRpc('barberium_customer_membership_actions_state',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token})])}
    const stateMap=Object.fromEntries((states||[]).map(x=>[x.membership_id,x]));const active=portal.memberships||[],requests=portal.membership_requests||[];const section=document.createElement('section');section.id='bmMembershipSection';section.className='bm-membership-section';const offers=(plans||[]).filter(p=>!active.some(m=>m.plan_id===p.id));
    section.innerHTML=`<div class="bm-title"><span>Benefícios</span><h2>Meus planos</h2></div>${session?.access_token?(active.length?`<div class="bm-plan-list">${active.map(m=>bmPlanCard(m,stateMap[m.id]||{})).join('')}</div>`:'<div class="bm-empty"><strong>Você ainda não possui assinatura ou pacote.</strong><p>Assinaturas aparecem por ciclo; pacotes mostram o saldo de créditos.</p></div>'):'<div class="bm-empty"><strong>Seus planos aparecerão aqui.</strong><p>Seu perfil é reconhecido após o primeiro agendamento neste aparelho.</p></div>'}${offers.length?`<div class="bm-title bm-offers-title"><span>Disponíveis</span><h2>Assinaturas e pacotes</h2></div><div class="bm-offer-list">${offers.map(p=>bmPublicPlanCard(p,requests,active.some(m=>m.plan_type===p.plan_type&&['pending','active','paused','overdue'].includes(m.status)))).join('')}</div>${session?.access_token?'<p class="bm-note">A solicitação não faz cobrança automática. A barbearia confirma a adesão e o pagamento integral antes de ativar o plano.</p>':'<p class="bm-note">Faça seu primeiro agendamento para poder solicitar um plano pelo site.</p>'}`:''}`;
    root.prepend(section);
    section.querySelectorAll('[data-bm-request]').forEach(btn=>btn.onclick=async()=>{if(!session?.access_token)return;btn.disabled=true;btn.textContent='Enviando…';try{await bmRpc('barberium_request_membership',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token,p_plan_id:btn.dataset.bmRequest});btn.textContent='Solicitação enviada';btn.classList.add('muted')}catch(e){btn.disabled=false;btn.textContent='Quero este plano';alert(e.message)}});
    section.querySelectorAll('[data-bm-pause]').forEach(btn=>btn.onclick=async()=>{const min=Number(btn.dataset.min)||1,max=Number(btn.dataset.max)||null;const raw=prompt(`Por quantos dias deseja solicitar a pausa?${max?` (${min} a ${max} dias)`:` (mínimo ${min} dia${min===1?'':'s'})`}`,String(min));if(raw===null)return;const days=Number(raw);if(!Number.isInteger(days)||days<min||(max&&days>max)){alert('Informe uma duração válida.');return}const note=prompt('Observação para a barbearia (opcional):')||'';btn.disabled=true;try{await bmRpc('barberium_customer_request_membership_action',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token,p_membership_id:btn.dataset.bmPause,p_action_type:'pause',p_requested_days:days,p_note:note||null});btn.textContent='Pausa solicitada';btn.classList.add('muted')}catch(e){btn.disabled=false;alert(e.message)}});
    section.querySelectorAll('[data-bm-cancel]').forEach(btn=>btn.onclick=async()=>{if(!confirm('Enviar solicitação de cancelamento desta assinatura? O ciclo já pago continua válido conforme a regra do plano.'))return;const note=prompt('Observação para a barbearia (opcional):')||'';btn.disabled=true;try{await bmRpc('barberium_customer_request_membership_action',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token,p_membership_id:btn.dataset.bmCancel,p_action_type:'cancel',p_requested_days:null,p_note:note||null});btn.textContent='Cancelamento solicitado';btn.classList.add('muted')}catch(e){btn.disabled=false;alert(e.message)}});
  }catch(e){console.error('Barberium planos:',e)}finally{bmBusy=false}
}

function bmSchedule(){clearTimeout(bmTimer);bmTimer=setTimeout(bmInject,80)}
document.addEventListener('click',e=>{if(e.target.closest('[data-nav="profile"]'))setTimeout(bmSchedule,80)});
const bmRoot=document.querySelector('#profileContent');if(bmRoot)new MutationObserver(()=>bmSchedule()).observe(bmRoot,{childList:true});
window.addEventListener('load',bmSchedule);

/* Reserva de benefício durante o agendamento v11.2 */
const bmBooking={serviceId:null,addons:new Set(),professionalId:null,date:null,time:null,selections:[]};
function bmSpParts(ts){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ts)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`}}
function bmResetBooking(){bmBooking.serviceId=null;bmBooking.addons=new Set();bmBooking.professionalId=null;bmBooking.date=null;bmBooking.time=null;bmBooking.selections=[]}
document.addEventListener('click',e=>{
  const t=e.target.closest('[data-service],[data-addon],[data-pro],[data-date],[data-time],[data-action="start-booking"],[data-nav="booking"]');if(!t)return;
  if(t.matches('[data-action="start-booking"],[data-nav="booking"]')){bmResetBooking();return}
  if(t.dataset.service){if(bmBooking.serviceId!==t.dataset.service)bmBooking.addons=new Set();bmBooking.serviceId=t.dataset.service}
  if(t.dataset.addon){bmBooking.addons.has(t.dataset.addon)?bmBooking.addons.delete(t.dataset.addon):bmBooking.addons.add(t.dataset.addon)}
  if(t.dataset.pro)bmBooking.professionalId=t.dataset.pro;if(t.dataset.date)bmBooking.date=t.dataset.date;if(t.dataset.time)bmBooking.time=t.dataset.time;
  setTimeout(bmBookingSchedule,80)
});
let bmBookingTimer=null;
function bmBookingSchedule(){clearTimeout(bmBookingTimer);bmBookingTimer=setTimeout(bmInjectBookingBenefit,120)}
async function bmInjectBookingBenefit(){const review=document.querySelector('#confirmBooking');const stage=document.querySelector('#bookingStage');const session=bmSession();if(!review||!stage||stage.querySelector('#bmBookingBenefit')||!session?.access_token||!bmBooking.serviceId||!bmBooking.date)return;try{await bmRpc('barberium_customer_refresh_membership_states',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token});const opts=await bmRpc('barberium_customer_membership_booking_options',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token,p_unit_slug:BM_UNIT,p_service_id:bmBooking.serviceId,p_addon_service_ids:[...bmBooking.addons],p_date:bmBooking.date});if(!opts?.length)return;const groups=Object.values(opts.reduce((acc,o)=>{const k=o.target_service_id;(acc[k]??={target:o.target_service,items:[]}).items.push(o);return acc},{}));const box=document.createElement('section');box.id='bmBookingBenefit';box.className='bm-booking-benefit';box.innerHTML=`<span class="bm-pill">Seu plano</span><h3>Usar benefício neste atendimento</h3><p>O benefício fica reservado agora e só conta como uso quando o atendimento for concluído.</p>${groups.map((g,gi)=>`<div class="bm-benefit-choice"><label>${bmEsc(g.target)}</label><select data-bm-benefit-group="${gi}"><option value="">Não usar benefício</option>${g.items.map((o,i)=>`<option value="${i}" ${g.items.length===1?'selected':''}>${bmEsc(o.plan)} • ${bmEsc(o.covered_service)} • abate ${bmMoney(o.coverage_cents)}${o.unlimited?' • ilimitado':` • ${o.available} uso${o.available===1?'':'s'} disp.`}</option>`).join('')}</select></div>`).join('')}<div id="bmBookingCoverage" class="bm-booking-coverage"></div>`;review.closest('.stage-actions')?.before(box);const update=()=>{bmBooking.selections=[];box.querySelectorAll('[data-bm-benefit-group]').forEach((sel,gi)=>{if(sel.value!=='')bmBooking.selections.push(groups[gi].items[Number(sel.value)])});const total=bmBooking.selections.reduce((t,x)=>t+Number(x.coverage_cents||0),0);box.querySelector('#bmBookingCoverage').textContent=total?`Benefícios selecionados: ${bmMoney(total)} de abatimento no fechamento.`:'Sem benefício selecionado.'};box.querySelectorAll('select').forEach(x=>x.onchange=update);update();review.addEventListener('click',()=>{if(bmBooking.selections.length)setTimeout(()=>bmReserveAfterBooking([...bmBooking.selections]),650)},{once:true})}catch(e){console.error('Benefícios do agendamento:',e)}}
async function bmReserveAfterBooking(selections){const session=bmSession();if(!session?.access_token||!selections.length)return;for(let attempt=0;attempt<12;attempt++){await new Promise(r=>setTimeout(r,attempt?450:0));try{const portal=await bmRpc('barberium_get_customer_portal',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token});const appt=(portal.appointments||[]).find(a=>{if(a.status!=='confirmed'||a.service?.id!==bmBooking.serviceId||a.professional?.id!==bmBooking.professionalId)return false;const pt=bmSpParts(a.starts_at);return pt.date===bmBooking.date&&pt.time===bmBooking.time});if(!appt)continue;for(const o of selections){try{await bmRpc('barberium_customer_reserve_membership_use',{p_barbershop_slug:BM_SHOP,p_access_token:session.access_token,p_appointment_id:appt.id,p_membership_id:o.membership_id,p_benefit_id:o.benefit_id,p_bucket_id:o.bucket_id,p_target_service_id:o.target_service_id})}catch(e){console.error('Reserva de benefício:',e)}}return}catch(e){console.error(e)}}}
const bmBookingStage=document.querySelector('#bookingStage');if(bmBookingStage)new MutationObserver(()=>bmBookingSchedule()).observe(bmBookingStage,{childList:true,subtree:false});
