// API simulada; não efetua alterações em produção. Requer Playwright e Chromium.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const f=path.join(root,new URL(req.url,'http://localhost').pathname);const target=fs.existsSync(f)&&fs.statSync(f).isDirectory()?path.join(f,'index.html'):f;if(!fs.existsSync(target)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(target))}).listen(8777,'127.0.0.1');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('barberium_staff_auth_v1',JSON.stringify({access_token:'mock-token'})));
const prof={id:'pr1',unit_id:'u1',name:'Vinicius'},unit={id:'u1',name:'Scalabrini Barbieri'},product={id:'p1',name:'Pomada Matte',category:'Finalizadores',description:'',sku:'PM01',price_cents:5000,cost_cents:2000,quantity:10,min_stock:2,is_active:true};let calls=[];
await page.route('https://pmvvawbaqylspxfmxezw.supabase.co/**',async route=>{const name=route.request().url().split('/').pop();const body=route.request().postDataJSON();calls.push({name,body});let data={};switch(name){case 'barberium_staff_me':data={role:'owner',barbershop_id:'b1',professional_id:'pr1'};break;case 'barberium_staff_catalog':data={units:[unit],professionals:[prof],services:[],permissions:{}};break;case 'barberium_staff_dashboard':data={appointments:[{id:'a1',customer:'Cliente Teste',professional:'Vinicius',service:'Corte',status:'confirmed',starts_at:'2026-09-16T15:00:00Z',ends_at:'2026-09-16T15:30:00Z',total_price_cents:9000}],blocks:[],summary:{total:1}};break;case 'barberium_staff_products':data=[product];break;case 'barberium_staff_product_stock_history':data=[];break;case 'barberium_staff_product_commission_config':data={professionals:[{...prof,default_percent:10,overrides:[]}],products:[product]};break;case 'barberium_staff_payment_options':data={providers:[]};break;case 'barberium_staff_checkout_products':data={sale_id:'s1'};break;case 'barberium_staff_product_sales':data=[];break;case 'barberium_staff_product_sale_detail':data={id:'s1',status:'completed',total_cents:10000,paid_cents:10000,completed_at:new Date().toISOString(),items:[{name:'Pomada Matte',quantity:2,line_total_cents:10000,commission_cents:1000}],payments:[{method:'pix',amount_cents:10000}]};break;case 'barberium_staff_appointment_detail':data={id:'a1',unit_id:'u1',professional:prof,customer:{name:'Cliente Teste'},service:{name:'Corte'},status:'confirmed',starts_at:'2026-09-16T15:00:00Z',ends_at:'2026-09-16T15:30:00Z',total_price_cents:9000};break;case 'barberium_staff_appointment_finance':data={total_price_cents:9000,membership_covered_cents:0,uses:[]};break;case 'barberium_staff_appointment_products':data={status:'draft',seller_professional_id:'pr1',total_cents:5000,items:[{product_id:'p1',quantity:1,name:product.name,line_total_cents:5000}]};break;case 'barberium_staff_product_report':data={net_revenue_cents:10000,units_sold:2,cost_cents:4000,top_products:[],low_stock:[]};break;}
await route.fulfill({contentType:'application/json',body:JSON.stringify(data)})});
await page.goto('http://127.0.0.1:8777/equipe/');await page.locator('#productsNav').click();await page.locator('.product-card').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(process.env.TEST_OUTPUT_DIR||'/tmp','barberium-products-mobile.png'),fullPage:true});
await page.locator('[data-edit-product]').click();await page.locator('#prName').fill('Pomada Premium');await page.locator('#productForm [type=submit]').click();await page.locator('.product-card').waitFor();assert(calls.find(x=>x.name==='barberium_staff_save_product').body.p_name==='Pomada Premium');
await page.locator('[data-stock-product]').click();await page.locator('#stockDelta').fill('3');await page.locator('#stockReason').fill('Entrada teste');await page.locator('#stockForm [type=submit]').click();await page.locator('.product-card').waitFor();
await page.locator('#counterSale').click();await page.locator('[data-basket-qty]').fill('2');await page.locator('#basketNext').click();await page.locator('#addProductPayment').click();const lines=page.locator('[data-payment-line]');await lines.nth(0).locator('[data-pay-amount]').fill('60,00');await lines.nth(1).locator('[data-pay-method]').selectOption('cash');await lines.nth(1).locator('[data-pay-amount]').fill('40,00');await lines.nth(1).locator('[data-pay-tender]').fill('50,00');assert((await lines.nth(1).locator('[data-pay-change]').innerText()).includes('10,00'));await page.screenshot({path:path.join(process.env.TEST_OUTPUT_DIR||'/tmp','barberium-payment-mobile.png'),fullPage:true});await page.locator('#completeProductSale').click();await page.locator('#refundProductSale').waitFor();const sale=calls.find(x=>x.name==='barberium_staff_checkout_products');assert.deepEqual(sale.body.p_payments.map(x=>x.amount_cents),[6000,4000]);assert.equal(sale.body.p_items[0].quantity,2);await page.locator('#modalClose').click();
await page.locator('[data-product-tab=commissions]').click();await page.locator('[data-product-commission]').click();await page.locator('[data-product-percent]').fill('20');await page.locator('#productCommissionForm [type=submit]').click();await page.locator('[data-product-commission]').waitFor();assert.equal(calls.find(x=>x.name==='barberium_staff_save_product_commission_config').body.p_overrides[0].percent,20);
await page.locator('[data-team-panel=agenda]').first().click();await page.locator('[data-appt-id]').click();await page.locator('#appointmentProductEdit').waitFor();await page.locator('[data-new-status=completed]').click();await page.locator('#finishAppointmentPayment').waitFor();assert.equal(await page.locator('[data-pay-amount]').inputValue(),'140,00');await page.locator('#finishAppointmentPayment').click();await page.locator('#modalBackdrop').waitFor({state:'hidden'});assert.equal(calls.find(x=>x.name==='barberium_staff_complete_appointment').body.p_payments[0].amount_cents,14000);
assert.deepEqual(errors,[]);console.log('PASS: mobile layout, product edit, stock, split payment/cash change, sale payload, commissions and combined checkout');await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
