begin;
do $$
declare m record; pr record; customer uuid; svc uuid; p uuid; sale uuid; ap uuid; ap2 uuid; req uuid:=gen_random_uuid(); r jsonb; before_fin jsonb; after_fin jsonb; n int; report jsonb;
begin
 select * into m from public.barbershop_members where role in ('owner','admin') and is_active and auth_user_id is not null limit 1;
 if m.id is null then raise exception 'Fixture: administrador ausente'; end if;
 perform set_config('request.jwt.claim.sub',m.auth_user_id::text,true);
 select * into pr from public.professionals where barbershop_id=m.barbershop_id and is_active limit 1;
 select id into customer from public.customers where barbershop_id=m.barbershop_id limit 1;
 select id into svc from public.services where barbershop_id=m.barbershop_id and unit_id=pr.unit_id and is_active limit 1;
 if customer is null or svc is null then raise exception 'Fixture: cliente/serviço ausente'; end if;
 r:=public.barberium_staff_save_product(null,'Teste transacional v12.3','Teste','Rollback',null,null,null,1000,2500,2,true,0);p:=(r->>'product_id')::uuid;
 perform public.barberium_staff_adjust_product_stock(p,pr.unit_id,10,'opening','Teste com rollback',1000);
 perform public.barberium_staff_save_product_commission_config(pr.id,10,jsonb_build_array(jsonb_build_object('product_id',p,'percent',20)));
 before_fin:=public.barberium_staff_finance_overview(current_date,current_date,pr.unit_id,'cash');
 r:=public.barberium_staff_checkout_products(req,pr.unit_id,customer,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),'[{"method":"pix","amount_cents":5000}]',0,null,'Teste');sale:=(r->>'sale_id')::uuid;
 if (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>8 then raise exception 'Baixa incorreta'; end if;
 if (select sum(amount_cents) from public.commission_entries where source_type='product_sale' and source_id in(select id from public.product_sale_items where sale_id=sale))<>1000 then raise exception 'Comissão personalizada incorreta'; end if;
 r:=public.barberium_staff_checkout_products(req,pr.unit_id,customer,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',2)),'[{"method":"pix","amount_cents":5000}]',0,null,'Teste');
 if (r->>'sale_id')::uuid<>sale or (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>8 then raise exception 'Idempotência falhou'; end if;
 after_fin:=public.barberium_staff_finance_overview(current_date,current_date,pr.unit_id,'cash');
 if (after_fin->>'gross_cents')::int-(before_fin->>'gross_cents')::int<>5000 then raise exception 'Financeiro duplicado/incorreto'; end if;
 report:=public.barberium_staff_finance_report(current_date,current_date,pr.unit_id,'cash');
 if not exists(select 1 from jsonb_array_elements(report->'payments') x where x->>'source_type'='product') then raise exception 'Produto ausente do relatório'; end if;
 perform public.barberium_staff_refund_product_sale(sale,'Teste estorno','pix');
 if (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>10 then raise exception 'Estorno estoque falhou'; end if;
 if (select sum(amount_cents) from public.commission_entries where (source_type='product_sale' and source_id in(select id from public.product_sale_items where sale_id=sale)) or (source_type='product_refund' and source_id=sale))<>0 then raise exception 'Estorno comissão falhou'; end if;
 begin perform public.barberium_staff_refund_product_sale(sale,'Repetição','pix');raise exception 'DOUBLE_REFUND_ALLOWED';exception when others then if sqlerrm='DOUBLE_REFUND_ALLOWED' then raise;end if;end;
 perform public.barberium_staff_save_commission_config(pr.id,50,'monthly','gross','[]');
 insert into public.appointments(barbershop_id,unit_id,professional_id,customer_id,service_id,starts_at,ends_at,base_price_cents,total_price_cents) values(m.barbershop_id,pr.unit_id,pr.id,customer,svc,'2090-01-01 12:00Z','2090-01-01 12:30Z',9000,9000) returning id into ap;
 perform public.barberium_staff_set_appointment_products(ap,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
 if (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>10 then raise exception 'Baixa antes da conclusão'; end if;
 r:=public.barberium_staff_complete_appointment(ap,'[{"method":"pix","amount_cents":11500}]',0,null,null);
 if (select sum(amount_cents) from public.appointment_payments where appointment_id=ap)<>9000 then raise exception 'Receita serviço misturada'; end if;
 if (select sum(pay.amount_cents) from public.product_sale_payments pay join public.product_sales ps on ps.id=pay.sale_id where ps.appointment_id=ap)<>2500 then raise exception 'Receita produto misturada'; end if;
 if (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>9 then raise exception 'Baixa conjunta incorreta'; end if;
 if (select sum(amount_cents) from public.commission_entries where appointment_id=ap and source_type='service')<>4500 then raise exception 'Comissão de serviços foi contaminada por produtos'; end if;
 begin perform public.barberium_staff_complete_appointment(ap,'[{"method":"pix","amount_cents":11500}]',0,null,null);raise exception 'DOUBLE_COMPLETE_ALLOWED';exception when others then if sqlerrm='DOUBLE_COMPLETE_ALLOWED' then raise;end if;end;
 insert into public.appointments(barbershop_id,unit_id,professional_id,customer_id,service_id,starts_at,ends_at,base_price_cents,total_price_cents) values(m.barbershop_id,pr.unit_id,pr.id,customer,svc,'2090-01-02 12:00Z','2090-01-02 12:30Z',9000,9000) returning id into ap2;
 perform public.barberium_staff_set_appointment_products(ap2,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)));
 perform public.barberium_staff_set_appointment_status(ap2,'cancelled');
 if exists(select 1 from public.product_sales where appointment_id=ap2) or (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>9 then raise exception 'Cancelamento rascunho incorreto'; end if;
 r:=public.barberium_staff_checkout_products(gen_random_uuid(),pr.unit_id,customer,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',1)),'[{"method":"pix","amount_cents":1000}]',1500,null,'Pendente');sale:=(r->>'sale_id')::uuid;
 perform public.barberium_staff_receive_product_balance(sale,'[{"method":"pix","amount_cents":1500}]');
 if (select pending_cents from public.product_sales where id=sale)<>0 then raise exception 'Recebimento saldo falhou'; end if;
 begin perform public.barberium_staff_checkout_products(gen_random_uuid(),pr.unit_id,customer,pr.id,jsonb_build_array(jsonb_build_object('product_id',p,'quantity',999)),'[{"method":"pix","amount_cents":2497500}]',0,null,null);raise exception 'NEGATIVE_STOCK_ALLOWED';exception when others then if sqlerrm='NEGATIVE_STOCK_ALLOWED' then raise;end if;end;
 if (select quantity from public.product_inventory where product_id=p and unit_id=pr.unit_id)<>8 then raise exception 'Falha não foi atômica'; end if;
 -- Product catalog must expose unit ID for selecting sellers, without leaking costs to a barber.
 if not exists(select 1 from jsonb_array_elements(public.barberium_staff_catalog()->'professionals') x where x->>'unit_id'=pr.unit_id::text) then raise exception 'Unidade ausente no catálogo'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.barberium_staff_products(pr.unit_id,null,true);raise exception 'ANON_ALLOWED';exception when others then if sqlerrm='ANON_ALLOWED' then raise;end if;end;
end $$;
select 'PASS: estoque, comissão personalizada, idempotência, estorno, cobrança conjunta, cancelamento, pendência, atomicidade e autenticação' result;
rollback;
